import { cp, mkdir, rm } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
const root = resolve(new URL('..', import.meta.url).pathname);
const dist = resolve(root, 'dist');
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(resolve(root, 'index.html'), resolve(dist, 'index.html'));
await cp(resolve(root, 'src'), resolve(dist, 'src'), { recursive: true });
await cp(resolve(root, 'data'), resolve(dist, 'data'), { recursive: true });
await cp(resolve(root, 'public'), resolve(dist, 'public'), { recursive: true });
console.log('Built dist/');
